data_quality_checks:
  null_checks:
    - table: "BRONZE.CUSTOMER"
      columns: ["CUSTOMER_ID", "EMAIL"]
    - table: "SILVER.ORDERS"
      columns: ["ORDER_ID", "CUSTOMER_ID"]
  
  unique_checks:
    - table: "BRONZE.CUSTOMER"
      columns: ["CUSTOMER_ID", "EMAIL"]
    - table: "SILVER.ORDERS"
      columns: ["ORDER_ID"]
  
  count_checks:
    - table: "BRONZE.CUSTOMER"
      min_count: 1
    - table: "SILVER.ORDERS"
      min_count: 1
